name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository code
    - name: 🛒 Checkout code
      uses: actions/checkout@v2

    # 2. Set up Java (JDK 21)
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # 3. Run Maven Build and Tests
    - name: Build with Maven
      run: mvn clean test

    # 4. Generate Allure Report
    - name: Generate Allure Report
      run: mvn allure:report

    # 5. Upload the generated Allure Report as Artifact
    - name: Upload Allure Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven-plugin/

    # Optional: Clean up (remove any temporary files, if needed)
    - name: Clean up
      run: rm -rf target/
