name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🛒 Checkout code
      uses: actions/checkout@v4

    - name: 🧰 Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: 🛠️ Build with Maven
      run: mvn clean install

    - name: 🧪 Run Tests and Generate Allure Report
      run: mvn test allure:report

    - name: 📤 Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/site/allure-maven-plugin

    - name: 🔐 Dependency Graph Snapshot (optional)
      uses: advanced-security/maven-dependency-submission-action@v4
